### ISSUE TITLE
How to disable request for `tex-svg.js` file?

### ISSUE THREAD

**Issue by battleoftwok** [plotly/plotly.rs#242]
The flag `plotly_embed_js` does not disable the file request https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-svg.js.
I need to disable all requests. Is it possible?

![Image](https://github.com/user-attachments/assets/9b5c9e00-c98e-4832-84b5-bd37fa34614c)

**Comment by battleoftwok** [comment]
#### Code:

```rust

let mut plot = Plot::new();
    let line = Scatter::new(coords.clone(), u.clone())
        .mode(Mode::LinesMarkers)
        .marker(Marker::new().size(10).opacity(0.8).color("#242424"));
plot.add_trace(line);
plot.show();

```

#### Cargo.toml
```toml

[dependencies]
nalgebra = "0.33.0"
nalgebra-sparse = "0.10.0"
ndarray = "0.13"
plotly = { version="0.10.0", features = ["plotly_embed_js"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_yml = "0.0.12"

```
